name: Generate Keystore (jalankan sekali)

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4.7.0
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Generate keystore
        run: |
          keytool -genkey -v \
            -keystore release.keystore \
            -alias hdapp \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=HD-APP, OU=Mobile, O=SyamsulHuda, L=Indonesia, S=Indonesia, C=ID" \
            -storepass hdapp123 \
            -keypass hdapp123

      - name: Save base64 to file
        run: base64 -w 0 release.keystore > keystore_base64.txt

      - name: Upload keystore artifact
        uses: actions/upload-artifact@v4
        with:
          name: keystore-base64
          path: keystore_base64.txt
          retention-days: 1
