name: Build & Release APK

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Java
        uses: actions/setup-java@v4.7.0
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: "stable"

      - name: Decrypt keystore
        run: |
          openssl enc -d -aes-256-cbc -salt -md sha256 \
            -in android/app/release.keystore.enc \
            -out android/app/release.keystore \
            -k ${{ secrets.KEYSTORE_ENCRYPT_PASSWORD }}
          ls -la android/app/release.keystore

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release
        env:
          KEY_STORE_PASSWORD: hdapp123
          KEY_PASSWORD: hdapp123
          KEY_ALIAS: hdapp

      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/HD-APP-${{ github.ref_name }}.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/HD-APP-${{ github.ref_name }}.apk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
